/**
 * BreakDownAPI
 * Backend API for the BreakDown app service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppUser from './AppUser';

/**
* The ServiceTicket model module.
* @module model/ServiceTicket
* @version 1.0.0
*/
export default class ServiceTicket {
    /**
    * Constructs a new <code>ServiceTicket</code>.
    * @alias module:model/ServiceTicket
    * @class
    * @param customer {module:model/AppUser} 
    * @param serviceLocation {String} 
    * @param serviceType {String} 
    */

    constructor(customer, serviceLocation, serviceType) {
        
        
        this['customer'] = customer;
        this['serviceLocation'] = serviceLocation;
        this['serviceType'] = serviceType;
        
    }

    /**
    * Constructs a <code>ServiceTicket</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServiceTicket} obj Optional instance to populate.
    * @return {module:model/ServiceTicket} The populated <code>ServiceTicket</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceTicket();
                        
            
            if (data.hasOwnProperty('ticketID')) {
                obj['ticketID'] = ApiClient.convertToType(data['ticketID'], 'String');
            }
            if (data.hasOwnProperty('dateCreated')) {
                obj['dateCreated'] = ApiClient.convertToType(data['dateCreated'], 'Date');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = AppUser.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('driver')) {
                obj['driver'] = AppUser.constructFromObject(data['driver']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('serviceLocation')) {
                obj['serviceLocation'] = ApiClient.convertToType(data['serviceLocation'], 'String');
            }
            if (data.hasOwnProperty('serviceDistance')) {
                obj['serviceDistance'] = ApiClient.convertToType(data['serviceDistance'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('serviceType')) {
                obj['serviceType'] = ApiClient.convertToType(data['serviceType'], 'String');
            }
            if (data.hasOwnProperty('custVehicle')) {
                obj['custVehicle'] = ApiClient.convertToType(data['custVehicle'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} ticketID
    */
    ticketID = undefined;
    /**
    * @member {Date} dateCreated
    */
    dateCreated = undefined;
    /**
    * @member {module:model/AppUser} customer
    */
    customer = undefined;
    /**
    * @member {module:model/AppUser} driver
    */
    driver = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {String} serviceLocation
    */
    serviceLocation = undefined;
    /**
    * @member {String} serviceDistance
    */
    serviceDistance = undefined;
    /**
    * @member {String} comments
    */
    comments = undefined;
    /**
    * @member {String} serviceType
    */
    serviceType = undefined;
    /**
    * @member {String} custVehicle
    */
    custVehicle = undefined;




}
