/**
 * BreakDownAPI
 * Backend API for the BreakDown app service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppUser from './AppUser';

/**
 * The ServiceTicket model module.
 * @module model/ServiceTicket
 * @version 1.0.0
 */
class ServiceTicket {
    /**
     * Constructs a new <code>ServiceTicket</code>.
     * @alias module:model/ServiceTicket
     * @param customer {module:model/AppUser} 
     * @param serviceLocation {String} 
     * @param serviceType {String} 
     */
    constructor(customer, serviceLocation, serviceType) { 
        
        ServiceTicket.initialize(this, customer, serviceLocation, serviceType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, customer, serviceLocation, serviceType) { 
        obj['customer'] = customer;
        obj['serviceLocation'] = serviceLocation;
        obj['serviceType'] = serviceType;
    }

    /**
     * Constructs a <code>ServiceTicket</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceTicket} obj Optional instance to populate.
     * @return {module:model/ServiceTicket} The populated <code>ServiceTicket</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceTicket();

            if (data.hasOwnProperty('ticketID')) {
                obj['ticketID'] = ApiClient.convertToType(data['ticketID'], 'String');
            }
            if (data.hasOwnProperty('dateCreated')) {
                obj['dateCreated'] = ApiClient.convertToType(data['dateCreated'], 'Date');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = AppUser.constructFromObject(data['customer']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('serviceLocation')) {
                obj['serviceLocation'] = ApiClient.convertToType(data['serviceLocation'], 'String');
            }
            if (data.hasOwnProperty('serviceDistance')) {
                obj['serviceDistance'] = ApiClient.convertToType(data['serviceDistance'], 'String');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
            }
            if (data.hasOwnProperty('serviceType')) {
                obj['serviceType'] = ApiClient.convertToType(data['serviceType'], 'String');
            }
            if (data.hasOwnProperty('custVehicle')) {
                obj['custVehicle'] = ApiClient.convertToType(data['custVehicle'], 'String');
            }
            if (data.hasOwnProperty('driver')) {
                obj['driver'] = AppUser.constructFromObject(data['driver']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} ticketID
 */
ServiceTicket.prototype['ticketID'] = undefined;

/**
 * @member {Date} dateCreated
 */
ServiceTicket.prototype['dateCreated'] = undefined;

/**
 * @member {module:model/AppUser} customer
 */
ServiceTicket.prototype['customer'] = undefined;

/**
 * @member {String} status
 */
ServiceTicket.prototype['status'] = undefined;

/**
 * @member {String} serviceLocation
 */
ServiceTicket.prototype['serviceLocation'] = undefined;

/**
 * @member {String} serviceDistance
 */
ServiceTicket.prototype['serviceDistance'] = undefined;

/**
 * @member {String} comments
 */
ServiceTicket.prototype['comments'] = undefined;

/**
 * @member {String} serviceType
 */
ServiceTicket.prototype['serviceType'] = undefined;

/**
 * @member {String} custVehicle
 */
ServiceTicket.prototype['custVehicle'] = undefined;

/**
 * @member {module:model/AppUser} driver
 */
ServiceTicket.prototype['driver'] = undefined;






export default ServiceTicket;

