/**
 * TestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TestData model module.
 * @module model/TestData
 * @version 1.0
 */
class TestData {
    /**
     * Constructs a new <code>TestData</code>.
     * @alias module:model/TestData
     */
    constructor() { 
        
        TestData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TestData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TestData} obj Optional instance to populate.
     * @return {module:model/TestData} The populated <code>TestData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TestData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
TestData.prototype['id'] = undefined;

/**
 * @member {String} name
 */
TestData.prototype['name'] = undefined;

/**
 * @member {String} date
 */
TestData.prototype['date'] = undefined;






export default TestData;

