/**
 * BreakDownAPI
 * Backend API for the BreakDown app service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceTicket from './ServiceTicket';

/**
* The TicketArray model module.
* @module model/TicketArray
* @version 1.0.0
*/
export default class TicketArray extends Array {
    /**
    * Constructs a new <code>TicketArray</code>.
    * @alias module:model/TicketArray
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>TicketArray</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TicketArray} obj Optional instance to populate.
    * @return {module:model/TicketArray} The populated <code>TicketArray</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TicketArray();
            ApiClient.constructFromObject(data, obj, 'ServiceTicket');
            
            
        }
        return obj;
    }





}
