/**
 * BreakDownAPI
 * Backend API for the BreakDown app service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AppUser from './model/AppUser';
import ServiceTicket from './model/ServiceTicket';
import Vehicle from './model/Vehicle';
import DefaultApi from './api/DefaultApi';
import ServiceTicketOpsApi from './api/ServiceTicketOpsApi';
import UserOpsApi from './api/UserOpsApi';


/**
* Backend_API_for_the_BreakDown_app_service_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BreakDownApi = require('index'); // See note below*.
* var xxxSvc = new BreakDownApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BreakDownApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BreakDownApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BreakDownApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AppUser model constructor.
     * @property {module:model/AppUser}
     */
    AppUser,

    /**
     * The ServiceTicket model constructor.
     * @property {module:model/ServiceTicket}
     */
    ServiceTicket,

    /**
     * The Vehicle model constructor.
     * @property {module:model/Vehicle}
     */
    Vehicle,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The ServiceTicketOpsApi service constructor.
    * @property {module:api/ServiceTicketOpsApi}
    */
    ServiceTicketOpsApi,

    /**
    * The UserOpsApi service constructor.
    * @property {module:api/UserOpsApi}
    */
    UserOpsApi
};
